/*
 * Copyright (c) 2023 by MILOSZ GILGA <https://miloszgilga.pl>
 * For check application license, check LICENSE file.
 */

export enum MachineModes {
  IDLE = 'IDLE',
  STOPPED = 'STOPPED',
  RUNNING = 'RUNNING',
  RESET = 'RESET',
  LOOP = 'LOOP',
  FINISH = 'FINISH',
  BACKWARD = 'BACKWARD',
  FORWARD = 'FORWARD',
  COMPILE_PROGRAM = 'COMPILE_PROGRAM',
  COMPILE_SUCCESSFUL = 'COMPILE_SUCCESSFUL',
  COMPILE_FAILURE = 'COMPILE_FAILURE',
  DEBUGGING = 'DEBUGGING',
  AJAX_ERROR_LOAD = 'AJAX_ERROR_LOAD',
  SUCCESSFULLY_LOAD_PROGRAM = 'SUCCESSFULLY_LOAD_PROGRAM',
}
